name: matjar_login_signup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_rating_bar: ^3.2.0+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: "^0.14.4"
  provider: ^4.3.2+1
  permission_handler: ^5.0.1+1
  firebase_database: ^4.4.0
  image_picker: ^0.6.7+4
  firebase_storage: ^5.2.0
  flutter_spinbox: ^0.3.1+2
  flutter:
    sdk: flutter
  mockito: ^4.1.3
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  
flutter_icons:
  image_path: "assets/logoApp.png"
  ios: true
  android: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/static/DancingScript-Regular.ttf
        
    - family: Matjar
      fonts:
        - asset: icons/Matjar.ttf

    - family: Matjar1
      fonts:
        - asset: icons/Matjar1.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

